### ISSUE TITLE
Skype images subject to copyright?

### ISSUE THREAD

**Issue by joker314** [WorldLanguages/isOnline#1]
I'm sure Skype does not allow use of their symbols. I think a more creative thing would be to create a green, red and grey version of the letter "S" in the scratch logo and use that.

**Comment by WorldLanguages** [comment]
@Gabric2 created versions of it but I haven't implemented them yet. I will add them pretty soon

**Comment by joker314** [comment]
Ok. Is Scratch down for you? They scheduled maintenance so it is possible.
