### ISSUE TITLE
It Completely Won't Work

### ISSUE THREAD

**Issue by OctoPenguin** [WorldLanguages/isOnline#10]
Hey everyone, OctoPenguin here. I'm a bit better known as TimeLordPlanet on Scratch. I discovered this extension because someone on the discussion forums told me that it would bring back the Discuss button. I installed the Firefox version but it won't open, instead doing this: 
![menu_008](https://user-images.githubusercontent.com/30018896/28665775-14b2af40-72c5-11e7-906a-6413afd4f38d.png)
Can you fix the issue?

**Comment by ALinuxLover** [comment]
use isOnlineV2

**Comment by joker314** [comment]
The main body of the extension is not the browser action (the button with the isOnline icon), but the changes that the extension makes to the content of your Scratch page (that is, the statuses [Online, Offline, etc.]).

If you wish to bring back the Discussion button, that is not done through the browser action either. Simply follow the instructions below to bring back the discussion button to the navigation panes.

1) Visit [@DiscussButton](https://scratch.mit.edu/users/DiscussButton/) on Scratch
2) Click on "Enable"
3) The page should reload the page automatically with the Discuss button now in the navigation pane. Thank you for using isOnline!

**Comment by OctoPenguin** [comment]
I got a reply from @isOnineV2 on Scratch, and he said that the button does not work in Firefox but will in the next edition.
