### ISSUE TITLE
Country selection / Somewhere else to store data

### ISSUE THREAD

**Issue by joker314** [WorldLanguages/isOnline#3]
People would like to still have their location visible. That leaves 2 options

* Find another place to store the data required for iO, such as profile descriptions, logo images, external database, etc.

* Store the location alongside the iO data. This has the drawback that you have to have the iO userscript to make it display, but at least it is better than something.

I'm going to try and make a PR implementing the second option, and then we can make it better later 😀

**Comment by JuegOStrower** [comment]
We are thinking store the location and isonline in the same spot.

----------------------------------
@JuegOStrower - helper and designer of isOnlie

**Comment by WorldLanguages** [comment]
I would go with the 2nd option first, to test if it is really requested by users

And after do the 1st one (that would be a big update)

**Comment by WorldLanguages** [comment]
OMG IT'S 12AM AND SCRATCH IS DOWN

**Comment by joker314** [comment]
YEAH I KNOW SO ANNOYING!!! Anyway, ye, I am working on storing it in with the location.

I am thinking `www.isonline.cf -> number United Kingdom` would work best?

Or maybe we should switch to using JSON in there?

By the way, we have to be careful that people don't start setting their location to rude words using inspect element, and us rendering it.

**Comment by JuegOStrower** [comment]
It would work to show your location to scratchers that use isOnline. But if a scratcher that don't use isOnline, wants to know the location: 

> www.isonline.cf -> number United Kingdom

scratch will show "Location not given".

**Comment by joker314** [comment]
Yes, that's a good point. But we should still do it.

**Comment by WorldLanguages** [comment]
@joker314 I would let people set countries and any two letter combination (ANY except ones that can be used to mean a bad word)

**Comment by WorldLanguages** [comment]
And I would add `country` ->``

**Comment by joker314** [comment]
Hmm, good idea.

**Comment by WorldLanguages** [comment]
omg this is real time

**Comment by joker314** [comment]
Yass!!!

**Comment by JuegOStrower** [comment]
yesss

**Comment by WorldLanguages** [comment]
@joker314 you aren't allowed to create a discord account, right?

**Comment by joker314** [comment]
Well, I don't want to, I don't like sharing my voice.
________________
How are we going to fetch the location? Do we make an extra request every time we update? Do we store it in localstorage and only update it every now-and-then?

**Comment by WorldLanguages** [comment]
@joker314 only for texting... if you deny its access to microphone or just don't accept calls it's just SMART texting

**Comment by WorldLanguages** [comment]
I never shared my voice either

**Comment by joker314** [comment]
What do you mean by "smart"?

**Comment by WorldLanguages** [comment]
There are 100+ scratchers on there, and there's an "isOnline users" server...

**Comment by joker314** [comment]
Hmm, ok. Link plz

**Comment by WorldLanguages** [comment]
discord.com create an account

remember to not mention discord on scratch, it wouldnt be allowed. i will delete this chat

**Comment by joker314** [comment]
Ok

**Comment by WorldLanguages** [comment]
tell me ur username later (its like: [name]#xxxx

**Comment by joker314** [comment]
Uhh.. the discord website looks weird.

**Comment by WorldLanguages** [comment]
oh wait, discordapp.com

**Comment by joker314** [comment]
Ah, thanks! :smile:

**Comment by WorldLanguages** [comment]
u dont have to download it
 
i use online version

**Comment by joker314** [comment]
I remember, somebody convinced me earlier to make an account. I think I am `jokebookservice1
#5422`

**Comment by WorldLanguages** [comment]
sended u invite

**Comment by joker314** [comment]
Thanks, I'm not really familiar with how everything works but I pressed the tick button next to your name

**Comment by JordanB-1337** [comment]
I have two ideas on where to store them, but I'd prefer to discuss them in private.

**Comment by WorldLanguages** [comment]
@JordanB-1337 please post them here, there is no PM in github

**Comment by JordanB-1337** [comment]
Yep, closing a 2 month old issue so we can all have a notification. :clap: :clap: :clap:
